name: Test condition run

on:
  push:
    branches: [ "action-test" ]
    tags:
      - '*'
    
  workflow_dispatch:
    branches: [ "action-test" ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Build and push Docker image to Azure Container Registry
      run: | 
        echo 'github sha'
        echo ${{ github.sha }}
        echo 'github tag'
        echo ${{ github.ref_name }}
        dockerTag=(( ${{ github.ref_name }} == "action-test" ? ${{ github.sha }} : ${{ github.ref_name }} ))  
        echo $dockerTag